name: "health_portfolio"
version: "1.0.0"
config-version: 2
profile: "health_profile"

models:
  health_portfolio:
    +materialized: view
    staging:
      +schema: staging
    marts:
      +schema: marts
